# Form implementation generated from reading ui file 'testWidget.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import clipboard

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(821, 771)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(40, 150, 191, 431))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 191, 41))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.addToClipboard = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.addToClipboard.setObjectName("addToClipboard")
        self.verticalLayout.addWidget(self.addToClipboard)
        self.clipboard = QtWidgets.QScrollArea(self.frame)
        self.clipboard.setGeometry(QtCore.QRect(0, 50, 191, 381))
        self.clipboard.setWidgetResizable(True)
        self.clipboard.setObjectName("clipboard")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 189, 379))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.clipboard.setWidget(self.scrollAreaWidgetContents)

        self.clipboard_content = []
        self.addToClipboard.clicked.connect(self.addToClipboardMethod)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setWindowFlags(QtCore.Qt.WindowType.FramelessWindowHint | QtCore.Qt.WindowType.WindowStaysOnTopHint)
        MainWindow.setAttribute(QtCore.Qt.WidgetAttribute.WA_TranslucentBackground)
        MainWindow.showMaximized()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.addToClipboard.setText(_translate("MainWindow", "Add to Clipboard"))
    
    def addToClipboardMethod(self):
        text = clipboard.paste()
        Clip = clipItem(text)
        print(text)
        self.verticalLayout_2.insertWidget(self.verticalLayout_2.count(), Clip.verticalLayoutWidget)
        self.clipboard_content.append(Clip)
        self.retranslateUi(MainWindow)

class clipItem():
    def __init__(self, clipname):
        self.text = clipname
        self.textEdit = QtWidgets.QTextEdit(self.text)
        self.textEdit.setReadOnly(True)
        self.copyButton = QtWidgets.QToolButton()
        self.copyButton.clicked.connect(self.copyFromClip)

        self.verticalLayoutWidget = QtWidgets.QWidget()
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0,0,50,50))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QHBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout.addWidget(self.textEdit)
        self.verticalLayout.addWidget(self.copyButton)

    def returnItems(self):
        return self.widgets
    
    def copyFromClip(self):
        clipboard.copy(self.text)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
